package com.menu_cocina.persistencia.entity;
// Generated 10/04/2019 12:07:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cocinero generated by hbm2java
 */
public class Cocinero  implements java.io.Serializable {


     private Integer idCocinero;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private Set detallefacturas = new HashSet(0);

    public Cocinero() {
    }

	
    public Cocinero(String nombre, String apellido1, String apellido2) {
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
    }
    public Cocinero(String nombre, String apellido1, String apellido2, Set detallefacturas) {
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.detallefacturas = detallefacturas;
    }
   
    public Integer getIdCocinero() {
        return this.idCocinero;
    }
    
    public void setIdCocinero(Integer idCocinero) {
        this.idCocinero = idCocinero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


