package com.menu_cocina.persistencia.entity;
// Generated 10/04/2019 12:07:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private DetallefacturaId id;
     private Cocinero cocinero;
     private Factura factura;
     private String plato;
     private String importe;
     private Date fechaFactura;

    public Detallefactura() {
    }

    public Detallefactura(DetallefacturaId id, Cocinero cocinero, Factura factura, String plato, String importe, Date fechaFactura) {
       this.id = id;
       this.cocinero = cocinero;
       this.factura = factura;
       this.plato = plato;
       this.importe = importe;
       this.fechaFactura = fechaFactura;
    }
   
    public DetallefacturaId getId() {
        return this.id;
    }
    
    public void setId(DetallefacturaId id) {
        this.id = id;
    }
    public Cocinero getCocinero() {
        return this.cocinero;
    }
    
    public void setCocinero(Cocinero cocinero) {
        this.cocinero = cocinero;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getPlato() {
        return this.plato;
    }
    
    public void setPlato(String plato) {
        this.plato = plato;
    }
    public String getImporte() {
        return this.importe;
    }
    
    public void setImporte(String importe) {
        this.importe = importe;
    }
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }




}


