package com.menu_cocina.persistencia.entity;
// Generated 10/04/2019 12:07:59 AM by Hibernate Tools 4.3.1



/**
 * DetallefacturaId generated by hbm2java
 */
public class DetallefacturaId  implements java.io.Serializable {


     private int idFactura;
     private int idDetalleFactura;

    public DetallefacturaId() {
    }

    public DetallefacturaId(int idFactura, int idDetalleFactura) {
       this.idFactura = idFactura;
       this.idDetalleFactura = idDetalleFactura;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public int getIdDetalleFactura() {
        return this.idDetalleFactura;
    }
    
    public void setIdDetalleFactura(int idDetalleFactura) {
        this.idDetalleFactura = idDetalleFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallefacturaId) ) return false;
		 DetallefacturaId castOther = ( DetallefacturaId ) other; 
         
		 return (this.getIdFactura()==castOther.getIdFactura())
 && (this.getIdDetalleFactura()==castOther.getIdDetalleFactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFactura();
         result = 37 * result + this.getIdDetalleFactura();
         return result;
   }   


}


