package com.menu_cocina.persistencia.entity;
// Generated 10/04/2019 12:07:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Camarero camarero;
     private Cliente cliente;
     private Mesa mesa;
     private Date fechaFactura;
     private Set detallefacturas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Camarero camarero, Cliente cliente, Mesa mesa, Date fechaFactura) {
        this.camarero = camarero;
        this.cliente = cliente;
        this.mesa = mesa;
        this.fechaFactura = fechaFactura;
    }
    public Factura(Camarero camarero, Cliente cliente, Mesa mesa, Date fechaFactura, Set detallefacturas) {
       this.camarero = camarero;
       this.cliente = cliente;
       this.mesa = mesa;
       this.fechaFactura = fechaFactura;
       this.detallefacturas = detallefacturas;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Camarero getCamarero() {
        return this.camarero;
    }
    
    public void setCamarero(Camarero camarero) {
        this.camarero = camarero;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


